- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ required_pkgs }}"

- name: Install pip packages
  pip:
    name:
      - docker
      - requests
    executable: "/usr/bin/pip3"

- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: docker-build
  register: docker_build_dir
  when: jenkins_custom_docker_image

- name: Copy jenkins Dockerfile
  template:
    src: "jenkins-Dockerfile.j2"
    dest: "{{ docker_build_dir.path }}/Dockerfile"
  when: jenkins_custom_docker_image

- name: Copy jenkins Dockerfile
  template:
    src: "jenkins-Dockerfile.j2"
    dest: "{{ docker_build_dir.path }}/Dockerfile"
  when: jenkins_custom_docker_image

- name: Copy entrypoint to build directory
  copy:
    src: "{{ item }}"
    dest: "{{ docker_build_dir.path }}/{{ item }}"
  when: jenkins_custom_docker_image 
  with_items:
    - entrypoint.sh

- name: Copy plug-in list to build directory
  copy:
    src: "{{ item }}"
    dest: "{{ docker_build_dir.path }}/{{ item }}"
  when: jenkins_custom_docker_image and jenkins_new_deploy
  with_items:
    - plugins.txt

- name: Copy JCasC config to build directory
  template:
    src: "jenkins-JCasC.yaml.j2"
    dest: "{{ docker_build_dir.path }}/jenkins.yaml"
  when: jenkins_custom_docker_image and jenkins_new_deploy
  vars:
    jenkins_id_ssh_rsa: "{{lookup('file', 'jenkins_id_ssh_rsa')}}"

- name: Add credentials to JCasC
  blockinfile:
    block: "{{ lookup('file', 'jenkins-credentials.yaml') }}"
    path: "{{ docker_build_dir.path }}/jenkins.yaml"
    marker: ""
  when: jenkins_custom_docker_image and jenkins_new_deploy
  ignore_errors: yes

- name: Build jenkins image
  docker_image:
    build:
      path: "{{ docker_build_dir.path }}"
      pull: yes
    name: jenkins-master
    source: build
    tag: latest
    force_tag: yes
    force_source: yes
  when: jenkins_custom_docker_image
  register: jenkins_image

#- name: Delete temporary directory
#  file:
#    state: absent
#    path: "{{ docker_build_dir.path }}"

- name: Create nginx-proxy container
  docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    restart_policy: unless-stopped

- name: Create letsencrypt container
  docker_container:
    name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    env:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart_policy: unless-stopped

- name: Create jenkins container
  docker_container:
    name: jenkins-master
    image: "{{ jenkins_image.image.RepoTags | join('\n') }}"
    ports:
      - "8080:8080"
    env:
      VIRTUAL_HOST: "{{ jenkins_fqdn }}"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "{{ jenkins_fqdn }}"
      LETSENCRYPT_EMAIL: "{{ jenkins_admin_email }}"
    volumes:
      - jenkins_home:/var/jenkins_home
    network_mode: bridge
    restart_policy: unless-stopped

- name: Get infos on volume
  docker_volume_info:
    name: jenkins_home
  register: volume_jenkins

- name: Pause play until a URL is reachable from this host
  uri:
    url: "https://{{ jenkins_fqdn }}/login"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 100
  delay: 5
  when: jenkins_new_deploy

#- name: Clean JCasC config file after jenkins deploy
#  file:
#    state: absent
#    path: "{{ volume_jenkins.volume.Mountpoint }}/jenkins.yaml"
#  when: jenkins_new_deploy

- name: Create daily backup script
  template:
    src: "jenkins_backup.j2"
    dest: "/etc/cron.daily/jenkins_backup"
    owner: root
    group: root
    mode: '0755'

- name: Populate jobs
  include: populate-jobs.yaml
  when: jenkins_new_deploy
