version: "3.4"
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
  fluentd:
    #image: fluent/fluentd:edge
    build:
      context: .
    depends_on:
      - influxdb
    ports:
      - 24224:24224/udp
    volumes:
      - fluentd-data:/fluentd/log
      - ./fluent.conf:/fluentd/etc/fluent.conf
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  fluentd-data:
  influxdb-data:
  grafana-data:
