---

- template:
    name: prepare-ut-sandbox
    streams:
      prepare-ut-sandbox:
        vars:
          LINUX_DISTR: centos
    jobs:
      prepare-sandbox-ut-sandbox:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: prepare-ut-sandbox
        vars:
          PUBLISH_TYPE: stable
          VM_TYPE: small
      # tox tests require just sources
      fetch-sources-ut-sandbox:
        job-name: build-fetch-sources
        stream: prepare-ut-sandbox
        depends-on:
          - prepare-sandbox-ut-sandbox
        vars:
          PUBLISH_TYPE: build
      # controller's UT requires a lot of stuff that is installed during configure stage
      # UI UT requires build deps from contrail-web-core/contrail-web-controller
      configure-ut-sandbox:
        job-name: build-configure
        stream: prepare-ut-sandbox
        depends-on:
          - fetch-sources-ut-sandbox
        vars:
          PUBLISH_TYPE: build
      cleanup-worker-ut-sandbox:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: prepare-ut-sandbox
        type: stream-post-hook
        depends-on:
          - configure-ut-sandbox

- template:
    name: test-unit
    parents:
      - prepare-ut-sandbox
    jobs:
      test-unit-agent:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-opserver:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-bgp:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-group-one:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-ungrouped:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS

# TODO: think about moving these below jobs into k8s cluster somehow
- template:
    name: test-unit-ui
    parents:
      - prepare-ut-sandbox
    jobs:
      test-unit-ui:
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG

- template:
    name: test-tox-pep8
    parents:
      - prepare-ut-sandbox
    jobs:
      test-unit-tox-pep8:
        job-name: test-unit-tox
        depends-on:
          - fetch-sources-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
        vars:
          TARGET_SET: pep8

- template:
    name: test-tox-unit
    parents:
      - prepare-ut-sandbox
    jobs:
      test-unit-tox-unit:
        job-name: test-unit-tox
        depends-on:
          - fetch-sources-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
        vars:
          TARGET_SET: unit

- template:
    name: test-tox-py36
    parents:
      - prepare-ut-sandbox
    jobs:
      test-unit-tox-py36:
        job-name: test-unit-tox
        depends-on:
          - fetch-sources-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
        vars:
          TARGET_SET: py36

- template:
    name: test-unit-go
    parents:
      - prepare-ut-sandbox
    jobs:
      test-unit-go:
        depends-on:
          - fetch-sources-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
