- name: create list
  set_fact:
    key_list: []

- name: include
  include: findkey.yaml
  with_items:
    - mirrors
    - logserver
    - jenkins_slave
    - workers
    - openlab1
    - openlab2
    - maas

- name: temlpate credentials
  template:
    src: jenkins-credentials.yaml.j2
    dest: "{{ docker_build_dir.path }}/jenkins-credentials.yaml"

- name: put credentials to JCasC
  shell: "cat {{ docker_build_dir.path }}/jenkins-credentials.yaml >> {{ docker_build_dir.path }}/jenkins.yaml"

- name: remove credentials file
  file:
    path: "{{ docker_build_dir.path }}/jenkins-credentials.yaml"
    state: absent
